### ISSUE TITLE
[Bug][SPARK] kyuubi.engine.submit.time is wrong for ApplicationMaster retries

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#5766] opened 2023-11-24 04:26 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
ERROR ApplicationMaster: User class threw exception: org.apache.kyuubi.KyuubiException: The total engine initialization time (84513834 ms) exceeds kyuubi.session.engine.initialize.timeout (300000 ms), and submitted at 1700714879267.
org.apache.kyuubi.KyuubiException: The total engine initialization time (84513834 ms) exceeds kyuubi.session.engine.initialize.timeout (300000 ms), and submitted at 1700714879267.
	at org.apache.kyuubi.engine.spark.SparkSQLEngine$.main(SparkSQLEngine.scala:319)
	at org.apache.kyuubi.engine.spark.SparkSQLEngine.main(SparkSQLEngine.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

When Kyuubi spark engine starting failover, the kyuubi.engine.submit.time is wrong to use

### Affects Version(s)

1.7.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment] 2023-11-24 04:27
cc @wForget

**Comment by wForget** [comment] 2023-11-24 09:43
Will the spark engine still work well after ApplicationMaster failover?

**Comment by yaooqinn** [comment] 2023-11-24 10:46
Not now maybe, but we shall make it work well

**Comment by pan3793** [comment] 2023-11-28 07:19
I think the current behavior is by design, I'm not sure changing the behavior is good idea since Kyuubi can create a new engine when a new session comes in if the previous engine is broken. If we change the behavior, the attempted engine launched after the new engine will waste resources, such behavior violates the original expectation

**Comment by wForget** [comment] 2023-11-30 11:25
> I think the current behavior is by design, I'm not sure changing the behavior is good idea since Kyuubi can create a new engine when a new session comes in if the previous engine is broken. If we change the behavior, the attempted engine launched after the new engine will waste resources, such behavior violates the original expectation

Your concern is reasonable, but the attempted engine failure should not be triggered by timeout. So, I think this fix can be accepted, and we can recommend users to set `spark.yarn.maxAppAttempts=1` before supporting attempted engines well. and cc @yaooqinn what do you think?

**Comment by yaooqinn** [comment] 2023-12-01 01:53
We can default spark.yarn.maxAppAttempts to 1

**Comment by wForget** [comment] 2023-12-07 07:43
@yaooqinn @pan3793 #5798 has been approved, I will merge it later. So is #5776 acceptable? If not I will close it later.

**Closed** 2023-12-07 12:06 UTC
Labels: kind:bug, priority:major
